apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tour-of-heroes-web
  name: tour-of-heroes-web
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: tour-of-heroes-web
  template:
    metadata:
      labels:
        app: tour-of-heroes-web
    spec:
      # securityContext:
      #   runAsNonRoot: true
      containers:
        - image: ghcr.io/0gis0/tour-of-heroes/tour-of-heroes:52506d3
          name: tour-of-heroes-web
          ports:
            - containerPort: 80
              name: web
          env:
            - name: API_URL
              value: http://tour-of-heroes-api-tour-of-heroes.apps-crc.testing/api/hero
